### PR TITLE
Fixed artist names and added more entries

### PR DESCRIPTION
**Pull request by Hakorr**
- new artists
- new emotions
- removed the "good" emotion
- one new color
- one new visual style

### CODE REVIEW

**Comment by cmdr2** [comment]
Hi @Hakorr , thanks for the change! This looks good, and nearly there, just two quick comments:

1. Can you please keep them sorted alphabetically?
2. Have you checked that prompts with the new special characters still produce the same output? E.g. Dali -> Dalí still produces the same painting style?

Thanks

**Comment by Hakorr** [comment]
Hey @cmdr2, 

1. Sorry for that, they are now sorted alphabetically. 
2. It seems like prompts with the new special characters have no effect on the output's style.

Note that along this fix, I added a couple more artist names and other entries.

**Comment by cmdr2** [comment]
Thanks! :)

**Comment by cmdr2** [comment]
Your changes are live @Hakorr ! :)

**Pull request merged**
