### PR TITLE
Add support for disabled state to model dropdown

### PR DESCRIPTION
**Pull request by patriceac**
As per https://discord.com/channels/1014774730907209781/1021695193499582494/1075068193753804831

The only limitation is that we cannot visually gray out the chevron itself because the corresponding font-awesome icon is a Pro icon (https://fontawesome.com/icons/angle-down?s=duotone&f=classic).

### CODE REVIEW

**Comment by JeLuF** [comment]
> we cannot visually gray out the chevron itself
Can't you change the text color of the chevron?

**Comment by patriceac** [comment]
Wait- what?!! It works indeed, but why? Aren't those icons images? 👀

**Comment by patriceac** [comment]
Code updated. Thanks JeLuf for pointing out this was possible!

**Comment by cmdr2** [comment]
Thanks!

**Pull request merged**
