### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by ChrisAcrobat**
This is essentially the same as #17, but does not source from my main branch.
I'll close #17 and edit all references that I can.

### CODE REVIEW

**Comment by godber** [comment]
The current master branch didn't work, nothing was listening on port 9000.  This PR here resolves that for me.  So 👍

**Comment by dsmmcken** [comment]
After this change 9000 no longer works for me.

**Comment by cmdr2** [comment]
@godber @dsmmcken Can you please check the new master? I've set the mapping to 9000:9000 and removed any server running at port 8000. This should hopefully resolve the problem. Thanks and apologies for the problem!

**Comment by godber** [comment]
Yeah, the current master (1ff9db3)  works on 9000 now.

**Comment by cmdr2** [comment]
Thanks @godber :)

**Pull request merged**
