### PR TITLE
Update for Amd cards?

### PR DESCRIPTION
**Pull request by Rizzlord**
Heya, love your work, but i got SD working for AMD, are there any plans for this version to get amd support instead of cpu?

### CODE REVIEW

**Comment by cmdr2** [comment]
Hi @Rizzlord Thanks. AMD isn't planned right now, but a user had success with installing this project inside a Docker container, and following the instructions at https://www.youtube.com/watch?v=d_CgaHyA_n4

If you're up for trying out the AMD approach, first install the rocm kernel module explained at the start of that video. You don't need the docker extension. Then please open your terminal, and then run:
`cd /path/to/stable-diffusion-ui`
`source installer/bin/activate`
`conda-unpack`
`cd stable-diffusion`
`conda activate ./env`
`pip install --upgrade torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.1.1` (the command from https://youtu.be/d_CgaHyA_n4?t=499)

Then re-run the `./start.sh` command.

**Comment by cmdr2** [comment]
Also, I can't tell if your PR has any code changes made by you, since it contains every code change made in the past few days by all the developers. If you have code changes to submit, can you please open a PR with only your code changes in it? You can check that by looking at the "files changed" tab. Thanks!

Closing this PR since it cannot be merged.

**Comment by itsagoodbrain** [comment]
Just FYI for anyone else that ends up here, I ended up fighting with the script a lot because it does a hard reset of the repo and the easiest way I found to make sure the right packages are installed is to modify environment.yaml so that the above listed pip command is included and the equivalent cuda packages are removed. If you locally commit the change you'll have a lot easier time. I ended up just going through the scripts manually, so it might break the updates, but I do have it working on AMD with roughly what was said above. 

P.S. To save a google for some, if you'll likely also need HSA_OVERRIDE_GFX_VERSION=10.3.0 if you have a gfx103* architecture... Most recent consumer cards.

**Comment by cmdr2** [comment]
Hi @itsagoodbrain I'm interested in integrating what worked for you, so that there is native support for AMD.

Can you please give a summary of the steps you took to make it work? I'd be happy to integrate that in. Even better would be a PR :)

Thanks

**Comment by itsagoodbrain** [comment]
I'll rework what changes I made into a PR. I'm pretty sure it won't be one you want to merge directly as it would break the CUDA version which is likely the majority of your users. I'll give some thought as to if there's a reasonable way for them to coexist unless you have thoughts. Some form of detection followed by a sed to modify the environment.yml or a separate one is all that comes to mind. Both feel kind of messy.

**Comment by cmdr2** [comment]
Thanks @itsagoodbrain Did you essentially follow the instructions I posted above? After installing the kernel module?

Or did it only work in a docker container? Thanks

**Comment by cmdr2** [comment]
https://github.com/cmdr2/stable-diffusion-ui/issues/115?notification_referrer_id=NT_kwDOAAzh_7E0MzYxODMzOTMxOjg0NDI4Nw

**Comment by powerfulaff** [comment]
I used this guide to get SD running on my amd GPU

https://gitgudblog.vercel.app/posts/stable-diffusion-amd-win10

I am not a coder as such but just wondering would this help to get the GUI running on a AMD card

**Pull request closed without merging**
