### PR TITLE
Add T600 to list of FP only GPUs

### PR DESCRIPTION
**Pull request by JeLuF**
https://discord.com/channels/1014774730907209781/1068948110304354314

### CODE REVIEW

**Comment by rbertus2000** [comment]
I found a full list of GPUs with this chip online:
https://www.techpowerup.com/gpu-specs/nvidia-tu117.g881
We can wait for the next one, or we just add mx450. mx550 and t1000 now.

**Comment by JeLuF** [comment]
The MXC450 and MX550 have 2GB max, we can ignore them

Looking at the code - isn't the T2000 check always `false`?
```py
 device_name = context.device_name.lower()
 'Quadro T2000' in device_name
 ```
 Should be `quadro`, no?

**Comment by rbertus2000** [comment]
> The MXC450 and MX550 have 2GB max, we can ignore them
> 
> Looking at the code - isn't the T2000 check always `false`?
> 
> ```python
>  device_name = context.device_name.lower()
>  'Quadro T2000' in device_name
> ```
> 
> Should be `quadro`, no?

I think so too, but do we even need 'quadro', when we check with txx in device_name?

**Comment by JeLuF** [comment]
Added t1000, and moved `quadro` in the same list as `nvidia` and `geforce`.
It's odd that the T2000 reports itself as Quadro T2000, while the T1200 is apparently  an NVIDIA T1200 or GEFORCE T1200.

**Comment by cmdr2** [comment]
Merged. Thanks @JeLuF and @rbertus2000 for this :)

**Pull request merged**
